// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Syntwin.Infrastructure.Persistence;

#nullable disable

namespace Syntwin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyntwinDbContext))]
    [Migration("20260717161937_AddFactoryRunCompiledProgramSnapshot")]
    partial class AddFactoryRunCompiledProgramSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Syntwin.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_audit_logs_created_at");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_audit_logs_robot_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_audit_logs_user_id");

                    b.HasIndex("RobotId", "CreatedAt")
                        .HasDatabaseName("IX_audit_logs_robot_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.CommandResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique()
                        .HasDatabaseName("UX_command_results_command_id");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_command_results_robot_id");

                    b.ToTable("command_results", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Asia/Ho_Chi_Minh");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_companies_created_by_user_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_companies_slug");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.CompanyMember", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_company_members_user_id");

                    b.HasIndex("CompanyId", "IsActive")
                        .HasDatabaseName("IX_company_members_company_active");

                    b.ToTable("company_members", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("LOGIN_CODE");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_email_otps_email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_email_otps_user_id");

                    b.HasIndex("Email", "Purpose", "ExpiresAt")
                        .HasDatabaseName("IX_email_otps_email_purpose_expires_at");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualStartSkewMs")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CoordinationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Synchronized");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailurePolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("IsolateTarget");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LuaContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuaContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LuaFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ScheduledStartAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepDurationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_factory_runs_company_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_factory_runs_created_by_user_id");

                    b.HasIndex("CompanyId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_factory_runs_company_status_created_at");

                    b.ToTable("factory_runs", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRunProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompiledProgramHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompiledProgramJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FactoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LuaContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuaContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LuaFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ProgramKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SyncPlanHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryRunId", "LuaContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_factory_run_programs_run_content_hash");

                    b.HasIndex("FactoryRunId", "ProgramKey")
                        .IsUnique()
                        .HasDatabaseName("UX_factory_run_programs_run_key");

                    b.ToTable("factory_run_programs", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRunTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ActualStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ArmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CommandReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EstimatedStepDurationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FactoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FactoryRunProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PrepareCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PrepareStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadinessError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReadyAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RuntimeSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StartLateByMs")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("IX_factory_run_targets_command_id");

                    b.HasIndex("FactoryRunId")
                        .HasDatabaseName("IX_factory_run_targets_factory_run_id");

                    b.HasIndex("FactoryRunProgramId")
                        .HasDatabaseName("IX_factory_run_targets_factory_run_program_id");

                    b.HasIndex("PrepareCommandId")
                        .HasDatabaseName("IX_factory_run_targets_prepare_command_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("IX_factory_run_targets_program_id");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_factory_run_targets_robot_id");

                    b.HasIndex("FactoryRunId", "RobotId")
                        .IsUnique()
                        .HasDatabaseName("UX_factory_run_targets_run_robot");

                    b.ToTable("factory_run_targets", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MerchantTransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PayDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MerchantTransactionRef")
                        .IsUnique()
                        .HasDatabaseName("UX_payment_transactions_merchant_transaction_ref")
                        .HasFilter("[MerchantTransactionRef] IS NOT NULL");

                    b.HasIndex("ProviderTransactionId")
                        .HasDatabaseName("IX_payment_transactions_provider_transaction_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_payment_transactions_status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_payment_transactions_subscription_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_payment_transactions_user_id");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_refresh_tokens_expires_at");

                    b.HasIndex("JwtId")
                        .HasDatabaseName("IX_refresh_tokens_jwt_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HTTP");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<Guid?>("RobotModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RobotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Registered");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_robots_company_id");

                    b.HasIndex("RobotModelId")
                        .HasDatabaseName("IX_robots_robot_model_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_robots_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_robots_user_id");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("IX_robots_company_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_robots_user_status");

                    b.ToTable("robots", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DeliveryAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastDeliveryAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("TimeoutAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_robot_commands_robot_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_robot_commands_user_id");

                    b.HasIndex("Status", "TimeoutAt")
                        .HasDatabaseName("IX_robot_commands_status_timeout_at");

                    b.HasIndex("RobotId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_robot_commands_robot_status_created_at");

                    b.ToTable("robot_commands", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultTcpFrame")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Dof")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JointLimitsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JointNamesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshRootPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UrdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_robot_models_is_active");

                    b.HasIndex("Vendor", "ModelCode")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_models_vendor_model_code");

                    b.ToTable("robot_models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f1e8d7a-5b7a-4a0f-8b2e-4e5d9f0f0005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultTcpFrame = "tool_link",
                            Description = "Fairino FR5 6-DOF collaborative robot model for simulator onboarding.",
                            DisplayName = "Fairino FR5",
                            Dof = 6,
                            IsActive = true,
                            JointLimitsJson = "[{\"joint\":1,\"minDeg\":-175,\"maxDeg\":175},{\"joint\":2,\"minDeg\":-265,\"maxDeg\":85},{\"joint\":3,\"minDeg\":-160,\"maxDeg\":160},{\"joint\":4,\"minDeg\":-265,\"maxDeg\":265},{\"joint\":5,\"minDeg\":-175,\"maxDeg\":175},{\"joint\":6,\"minDeg\":-175,\"maxDeg\":175}]",
                            JointNamesJson = "[\"j1\",\"j2\",\"j3\",\"j4\",\"j5\",\"j6\"]",
                            MeshRootPath = "/fairino_description/meshes/fairino5_v6",
                            ModelCode = "FR5",
                            UrdfPath = "/fairino_description/urdf/fairino5_v6.urdf",
                            Vendor = "Fairino"
                        });
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Studio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_robot_programs_created_by_user_id");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_robot_programs_robot_id");

                    b.HasIndex("RobotId", "Status")
                        .HasDatabaseName("IX_robot_programs_robot_status");

                    b.ToTable("robot_programs", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotProgramStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("IX_robot_program_steps_program_id");

                    b.HasIndex("ProgramId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_program_steps_program_order");

                    b.ToTable("robot_program_steps", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotRuntimeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DetectedOfflineAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_runtime_sessions_robot_open")
                        .HasFilter("[EndedAt] IS NULL");

                    b.HasIndex("RobotId", "EndedAt")
                        .HasDatabaseName("IX_robot_runtime_sessions_robot_ended_at");

                    b.HasIndex("RobotId", "StartedAt")
                        .HasDatabaseName("IX_robot_runtime_sessions_robot_started_at");

                    b.HasIndex("RobotId", "EndedAt", "EndReason")
                        .HasDatabaseName("IX_robot_runtime_sessions_robot_ended_at_reason");

                    b.ToTable("robot_runtime_sessions", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotSafetyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PolicyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RobotModel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_robot_safety_policies_company_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("IX_robot_safety_policies_robot_id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CompanyId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_safety_policies_company_active")
                        .HasFilter("[RobotId] IS NULL AND [IsActive] = 1");

                    b.HasIndex("RobotId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_safety_policies_robot_active")
                        .HasFilter("[RobotId] IS NOT NULL AND [IsActive] = 1");

                    b.HasIndex("CompanyId", "Scope", "IsActive")
                        .HasDatabaseName("IX_robot_safety_policies_company_scope_active");

                    b.HasIndex("RobotId", "Scope", "IsActive")
                        .HasDatabaseName("IX_robot_safety_policies_robot_scope_active");

                    b.ToTable("robot_safety_policies", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotSceneBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BaseX")
                        .HasColumnType("float");

                    b.Property<double>("BaseY")
                        .HasColumnType("float");

                    b.Property<double>("BaseYaw")
                        .HasColumnType("float");

                    b.Property<double>("BaseZ")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GraphPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PrimPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RosNamespace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SceneType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("FairinoStudio");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UrdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique()
                        .HasDatabaseName("UX_robot_scene_bindings_robot_id");

                    b.HasIndex("SceneType", "RobotId")
                        .HasDatabaseName("IX_robot_scene_bindings_scene_robot");

                    b.ToTable("robot_scene_bindings", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuditRetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("CanSendCommand")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView3D")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRobots")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_subscription_plans_code");

                    b.ToTable("subscription_plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditRetentionDays = 7,
                            CanSendCommand = false,
                            CanView3D = false,
                            Code = "Free",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MaxRobots = 1,
                            MonthlyPrice = 0m,
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            AuditRetentionDays = 30,
                            CanSendCommand = false,
                            CanView3D = true,
                            Code = "Basic",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MaxRobots = 3,
                            MonthlyPrice = 99000m,
                            Name = "Basic"
                        },
                        new
                        {
                            Id = 3,
                            AuditRetentionDays = 365,
                            CanSendCommand = true,
                            CanView3D = true,
                            Code = "Premium",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MaxRobots = 10,
                            MonthlyPrice = 299000m,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_users_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_user_subscriptions_plan_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_user_subscriptions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_subscriptions_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_user_subscriptions_user_status");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Robot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.CommandResult", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.RobotCommand", "Command")
                        .WithOne("Result")
                        .HasForeignKey("Syntwin.Domain.Entities.CommandResult", "CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("CommandResults")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Company", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedCompanies")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.CompanyMember", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Company", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.EmailOtp", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRun", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRunProgram", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.FactoryRun", "FactoryRun")
                        .WithMany("Programs")
                        .HasForeignKey("FactoryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryRun");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRunTarget", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.RobotCommand", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Syntwin.Domain.Entities.FactoryRun", "FactoryRun")
                        .WithMany("Targets")
                        .HasForeignKey("FactoryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.FactoryRunProgram", "FactoryRunProgram")
                        .WithMany("Targets")
                        .HasForeignKey("FactoryRunProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Syntwin.Domain.Entities.RobotCommand", "PrepareCommand")
                        .WithMany()
                        .HasForeignKey("PrepareCommandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Syntwin.Domain.Entities.RobotProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("FactoryRun");

                    b.Navigation("FactoryRunProgram");

                    b.Navigation("PrepareCommand");

                    b.Navigation("Program");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.UserSubscription", "Subscription")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Robot", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Company", "Company")
                        .WithMany("Robots")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.RobotModel", "RobotModel")
                        .WithMany("Robots")
                        .HasForeignKey("RobotModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("RobotModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotCommand", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("Commands")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Robot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotProgram", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("Programs")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotProgramStep", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.RobotProgram", "Program")
                        .WithMany("Steps")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotRuntimeSession", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("RuntimeSessions")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotSafetyPolicy", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Company", "Company")
                        .WithMany("SafetyPolicies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithMany("SafetyPolicies")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Syntwin.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Robot");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotSceneBinding", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.Robot", "Robot")
                        .WithOne("SceneBinding")
                        .HasForeignKey("Syntwin.Domain.Entities.RobotSceneBinding", "RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("Syntwin.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Syntwin.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Company", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Robots");

                    b.Navigation("SafetyPolicies");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRun", b =>
                {
                    b.Navigation("Programs");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.FactoryRunProgram", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.Robot", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CommandResults");

                    b.Navigation("Commands");

                    b.Navigation("Programs");

                    b.Navigation("RuntimeSessions");

                    b.Navigation("SafetyPolicies");

                    b.Navigation("SceneBinding");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotCommand", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotModel", b =>
                {
                    b.Navigation("Robots");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.RobotProgram", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.User", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("CreatedCompanies");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Syntwin.Domain.Entities.UserSubscription", b =>
                {
                    b.Navigation("PaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
