name: syntwin

services:
  syntwin-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syntwin-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SyntwinDb=Server=syntwin-sqlserver;Database=SyntwinDb;User=sa;Password=${SQLSERVER_SA_PASSWORD};TrustServerCertificate=True
      - Redis__ConnectionString=syntwin-redis:6379
      - Jwt__SigningKey=${JWT_SIGNING_KEY}
      - Seed__SuperAdmin__Password=${SUPERADMIN_PASSWORD}
    depends_on:
      - syntwin-sqlserver
      - syntwin-redis
    networks:
      - syntwin_network

  syntwin-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: syntwin-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "${SQLSERVER_PORT}:1433"
    volumes:
      - syntwin_sql_data:/var/opt/mssql
    networks:
      - syntwin_network
      
  syntwin-redis:
    image: redis:7-alpine
    container_name: syntwin-redis
    ports:
      - "16379:6379"
    networks:
      - syntwin_network
volumes:
  syntwin_sql_data:

networks:
  syntwin_network:
    driver: bridge